import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { persons, gifts, occasions } from "@/lib/db/schema";
import { eq, asc } from "drizzle-orm";

export async function GET() {
  const allPersons = db.select().from(persons).orderBy(asc(persons.name)).all();

  let html = `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Geschenke-Manager — Full List</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 2rem; max-width: 900px; margin: 0 auto; color: #1a1a1a; }
    h1 { font-size: 1.8rem; margin-bottom: 0.5rem; }
    .subtitle { color: #666; margin-bottom: 2rem; }
    .person { border: 1px solid #e5e5e5; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
    .person h2 { font-size: 1.3rem; margin-bottom: 0.25rem; }
    .person .info { color: #666; font-size: 0.9rem; margin-bottom: 1rem; }
    .gift { background: #f8f8f8; border-radius: 6px; padding: 0.75rem 1rem; margin-bottom: 0.5rem; }
    .gift h3 { font-size: 0.95rem; }
    .gift .meta { font-size: 0.8rem; color: #888; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 500; }
    .badge-idea { background: #fef3c7; color: #92400e; }
    .badge-gift { background: #d1fae5; color: #065f46; }
    .badge-purchased { background: #dbeafe; color: #1e40af; }
    a { color: #2563eb; }
    .empty { color: #999; font-style: italic; }
    .generated { text-align: center; color: #999; font-size: 0.8rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #eee; }
  </style>
</head>
<body>
  <h1>Geschenke-Manager</h1>
  <p class="subtitle">Full list — Generated on ${new Date().toLocaleDateString("de-DE")}</p>
`;

  for (const person of allPersons) {
    const personGifts = db
      .select({
        id: gifts.id,
        title: gifts.title,
        description: gifts.description,
        link: gifts.link,
        giftDate: gifts.giftDate,
        isIdea: gifts.isIdea,
        isPurchased: gifts.isPurchased,
        occasionName: occasions.name,
      })
      .from(gifts)
      .leftJoin(occasions, eq(gifts.occasionId, occasions.id))
      .where(eq(gifts.personId, person.id))
      .all();

    html += `  <div class="person">
    <h2>${escapeHtml(person.name)}</h2>
    <p class="info">Birthday: ${person.birthday}${person.notes ? ` — ${escapeHtml(person.notes)}` : ""}</p>
`;

    if (personGifts.length === 0) {
      html += `    <p class="empty">No gifts or ideas recorded.</p>\n`;
    } else {
      for (const gift of personGifts) {
        const badges: string[] = [];
        if (gift.isIdea) badges.push('<span class="badge badge-idea">Idea</span>');
        else badges.push('<span class="badge badge-gift">Gift</span>');
        if (gift.isPurchased) badges.push('<span class="badge badge-purchased">Purchased</span>');

        html += `    <div class="gift">
      <h3>${escapeHtml(gift.title)} ${badges.join(" ")}${gift.occasionName ? ` <span class="meta">— ${escapeHtml(gift.occasionName)}</span>` : ""}</h3>
      ${gift.description ? `<p class="meta">${escapeHtml(gift.description)}</p>` : ""}
      ${gift.link ? `<p class="meta"><a href="${escapeHtml(gift.link)}" target="_blank">${escapeHtml(gift.link)}</a></p>` : ""}
      ${gift.giftDate ? `<p class="meta">Date: ${gift.giftDate}</p>` : ""}
    </div>\n`;
      }
    }

    html += `  </div>\n`;
  }

  html += `  <p class="generated">Generated by Geschenke-Manager</p>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": "attachment; filename=geschenke-liste.html",
    },
  });
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
